# Generated by Django 6.0.4 on 2026-05-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_job_company_name_job_min_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='phone',
            field=models.CharField(default='0000000000', max_length=15),
            preserve_default=False,
        ),
    ]
